all:
	@echo "--nothing to be done for make in Shell Script--"

clean:
	rm -f *~
	rm -rf *#*

distclean: clean
	rm -f vars.sh
	rm -f Makefile.rules

check:
	@echo "--!! CHECK target not implemented for Shell Script !!--"
