all:
	@echo "--nothing to be done for make in Python--"

clean:
	rm -f *~
	rm -rf *#*
	find . -name "*~" -exec rm -rf '{}' \;
	find . -name "*#*" -exec rm -rf '{}' \;
	find . -name "*.class" -exec rm -rf '{}' \;

distclean: clean

check:
	@echo "--!! CHECK target not implemented for Python !!--"
